version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
      - STOCK_API_KEY=${STOCK_API_KEY}
    volumes:
      - /mnt/tank/stone/git/Dividend-Bot/config.json:/app/config.json